Add tika parsers to improve mime type detection
The plain tika-parsers package doesn't have implementations,
but tika-parsers-standard-package does.

Commented for now because it makes the jar fail to start:

    $ java -jar ripme.jar
    Error: A JNI error has occurred, please check your installation and try again
    Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
            at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:339)
            at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:281)
            at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:279)
            at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:235)
            at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:739)
            at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1049)
            at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:42)
            at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.getManifest(URLClassPath.java:720)
            at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:762)
            at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:691)
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:620)
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:578)
            at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
            at java.base/java.lang.Class.forName0(Native Method)
            at java.base/java.lang.Class.forName(Class.java:547)
            at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:860)
            at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:745)